name             "ontohub"
maintainer       "James A. Overton"
maintainer_email "james@overton.ca"
license          "MIT"
description      "Installs Ontohub"
long_description "TODO"
version          "0.0.1"

supports "ubuntu"
supports "debian"

depends "apt", ">= 1.9.0"
depends "hets", ">= 0.0.1"
depends "ruby"
depends "rvm"
depends "postgresql"
