#!/usr/bin/env ruby
# 
# This file was placed here by Ontohub.
# It makes sure that your pushed commits will be processed properly.
# 

require File.expand_path('../../lib/init',  File.realdirpath(__FILE__))
require 'git_update'

key_id    = ENV['KEY_ID']
repo_path = `pwd`
refname, oldrev, newrev = GitUpdate.retrieve_update_environment

GitUpdate.update_redis(repo_path, oldrev, newrev, refname, key_id)
