#!/bin/bash

# Installing Dependencies
sudo apt-add-repository ppa:hets/hets
sudo apt-add-repository "deb http://archive.canonical.com/ubuntu precise partner"
sudo apt-get update

sudo apt-get install -y build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion postgresql redis-server hets-core libqtwebkit-dev

# RVM
curl -L https://get.rvm.io | bash -s stable --ruby
source $HOME/.rvm/scripts/rvm
echo "source $HOME/.rvm/scripts/rvm" >> ~/.bashrc
sudo addgroup rvm
sudo adduser $USER rvm

# Workarounds
sudo ln -s /lib/x86_64-linux-gnu/libpng12.so.0 /lib/x86_64-linux-gnu/libpng14.so.14

# Installing bundler and ontohub dependencies
gem install bundler
bundle install

# Write database configuration
cat > config/database.yml <<EOF
development: &config
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  template: template0
  database: ontohub_development
  username: postgres
  password:
  pool: 5

test:
  <<: *config
  database: ontohub_test

production:
  <<: *config
  database: ontohub
  username: ontohub
EOF

# Configuring Ontohub
rake db:migrate:reset
rake sunspot:solr:start
rake db:seed
rake sunspot:solr:stop
